"""add completed_at timestamp

Revision ID: 63aaa57ec2a7
Revises: de6ccf8c4989
Create Date: 2026-07-03 22:52:22.571746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63aaa57ec2a7'
down_revision = 'de6ccf8c4989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
